name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18, 19]
        mongodb-version: ['4.0', '5.0', '6.0']

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}  
  
    - run: npm install
    - run: npm test
    
    - name: Test Reporter
      uses: dorny/test-reporter@v1.6.0
      if: success() || failure()    # run this step even if previous step failed
      with:
        artifact: test-results            # artifact name
        name: JEST Tests                  # Name of the check run which will be created
        path: '*.xml'                     # Path to test results (inside artifact .zip)
        reporter: jest-junit              # Format of test results
